---
version: '1.0'
description: "A workflow that can be used as a pipeline for Terraform execution"

input:
  - backend
  - plan_path
  - terraform_exec
  - workspace
  - variable_dict
  - variable_files
  - destroy
  - timeout

vars:
  - results: {}

output:
  - results: <% ctx().apply_result %>

tasks:
  init:
    action: terraform.init

    input:
      backend: <% ctx().backend %>
      plan_path: <% ctx().plan_path %>
      terraform_exec: <% ctx().terraform_exec %>

    next:
      - when: <% succeeded() %>
        do:
          - select_workspace

  select_workspace:
    action: terraform.select_workspace

    input:
      plan_path: <% ctx().plan_path %>
      terraform_exec: <% ctx().terraform_exec %>
      workspace: <% ctx().workspace %>

    next:
      - when: <% succeeded() %>
        do:
          - plan
      - when: <% failed() %>
        do:
          - create_workspace

  create_workspace:
    action: terraform.create_workspace

    input:
      plan_path: <% ctx().plan_path %>
      terraform_exec: <% ctx().terraform_exec %>
      workspace: <% ctx().workspace %>

    next:
      - when: <% succeeded() %>
        do:
          - plan

  plan:
    action: terraform.plan

    input:
      plan_path: <% ctx().plan_path %>
      terraform_exec: <% ctx().terraform_exec %>
      variable_dict: <% ctx().variable_dict %>
      variable_files: <% ctx().variable_files %>

    next:
      - when: <% succeeded() and not ctx().destroy %>
        do:
          - apply
      - when: <% succeeded() and ctx().destroy %>
        do:
          - destroy

  apply:
    action: terraform.apply

    input:
      plan_path: <% ctx().plan_path %>
      terraform_exec: <% ctx().terraform_exec %>
      variable_dict: <% ctx().variable_dict %>
      variable_files: <% ctx().variable_files %>
      timeout: <% ctx(timeout) %>
    next:
      - when: <% succeeded() %>
        publish:
          - results: <% result().result %>

  destroy:
    action: terraform.destroy

    input:
      plan_path: <% ctx().plan_path %>
      terraform_exec: <% ctx().terraform_exec %>
      variable_dict: <% ctx().variable_dict %>
      variable_files: <% ctx().variable_files %>
      timeout: <% ctx(timeout) %>
    next:
      - when: <% succeeded() %>
        publish:
          - results: <% result().result %>
